{% set name = "acquifer" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/acquifer-{{ version }}.tar.gz
  sha256: 06e0204fb642f101516e53c640bcbf776b2ae15fc91cc5f02db488ac43b567bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - dask-image
    - numpy
    - python >={{ python_min }}
    - sortedcontainers
    - xarray

test:
  imports:
    - acquifer
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/acquifer/Acquifer-Python-API
  summary: Utilitary functions when working with image datasets acquired with an ACQUIFER Imaging Machine microscope
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - LauLauThom
